# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "epc" do |epc|
    epc.vm.box = "bento/ubuntu-17.10"


# IDEALLY, this is the only line we need to write. In practice, the combo of
# Vagrant + Ubuntu > 15.10 has unresolved net config issues, unclear why.
#    epc.vm.network "private_network", ip: "10.0.101.3"
#    epc.vm.network "public_network", ip: "10.0.200.3"

# (If the issues ever get resolved, delete the lines below this comment)
#   epc.vm.provision 'shell', inline: "ifconfig eth1 up"
    epc.vm.network "private_network", ip: "10.0.101.3", auto_config: false
    epc.vm.network "public_network", ip: "10.0.200.3", auto_config: false
    epc.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    epc.vm.provision 'shell', inline: "ifconfig eth1 10.0.101.3", run: "always"
    epc.vm.provision 'shell', inline: "ifconfig eth2 10.0.200.3", run: "always"

    epc.vm.provision "ansible" do |ansible|
      ansible.playbook = "epc_playbook.yml"
    end
  end

  config.vm.define "enb" do |enb|
    enb.vm.box = "bento/ubuntu-14.04"

    # (oaisim needs extra memory)
    enb.vm.provider "virtualbox" do |vb|
      vb.customize ['modifyvm', :id, '--natnet1', '10.0.100.0/24']
      vb.memory = 2048
    end

    enb.vm.network "private_network", ip: "10.0.101.2"

    enb.vm.provision "ansible" do |ansible|
      ansible.playbook = "enb_playbook.yml"
    end
  end

end
