# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

   config.vm.box = "bento/ubuntu-14.04"
#  config.vm.provision :shell, path: "bootstrap.sh"

   config.vm.provider "virtualbox" do |vb|
     vb.customize ['modifyvm', :id, '--natnet1', '10.0.100.0/24']
     vb.memory = 2048
   end

   config.vm.network "private_network", ip: "10.0.101.2"
  
   config.vm.provision "ansible" do |ansible|
     ansible.playbook = "playbook.yml"
   end

  # config.vm.box_check_update = false

  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  # config.vm.synced_folder "../data", "/vagrant_data"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
