# SMS TODO: CHECK FOR INSTALLATION AND ABORT IF WE ALREADY HAVE THIS INSTALLED

# ---
# - hosts: all

#   tasks:
    - name: freeDiameter - apt-get update
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: freeDiameter - apt-get necessary packages
      apt:
        name: "{{ item }}"            
      with_items:
      - autoconf
      - automake
      - bison
      - build-essential
      - cmake
      - cmake-curses-gui
      - debhelper
      - flex
      - g++
      - gcc
      - gdb
      - libgcrypt-dev
      - libgnutls28-dev
      - libidn11-dev
      - libmysqlclient-dev
      - libpq-dev
      - libsctp1
      - libsctp-dev
      - libxml2-dev
      - mercurial
      - python-dev
      - ssl-cert
      - swig
      become: yes

    - name: freeDiameter - clone from my github copy
      git:
        repo: https://github.com/spencersevilla/freediameter.git
        dest: /home/"{{ username }}"/freediameter

    - name: freeDiameter - cmake prep
      shell: |
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local ../
      args:
        chdir: /home/"{{ username }}"/freediameter

    - name: freeDiameter - build
      make:
        chdir: /home/"{{ username }}"/freediameter

    - name: freeDiameter - install
      make:
        chdir: /home/"{{ username }}"/freediameter
        target: install
      become: yes
