---
- hosts: localhost
  vars:
    mysql_user: enbrain
    username: enbrain
    mysql_password: correcthorsebatterystaple
  # vars_prompt:
  #     - name: mysql_password_unused
  #       prompt: "please enter a mysql db password"
  become_user: enbrain

############################################################################
################################## HSS #####################################
############################################################################

  tasks:
    - name: apt-get update
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: pre-configure phpmyadmin
      debconf:
        name: phpmyadmin 
        question: "{{ item.name }}"
        vtype: "{{ item.type }}"
        value: "{{ item.val }}"
      with_items:
        - {name: phpmyadmin/dbconfig-install, type: boolean, val: true}
        - {name: phpmyadmin/app-password-confirm, type: password, val: "{{ mysql_password }}"}
        - {name: phpmyadmin/mysql/admin-pass, type: password, val: "{{ mysql_password }}"}
        - {name: phpmyadmin/mysql/app-pass, type: password, val: "{{ mysql_password }}"}
        - {name: phpmyadmin/reconfigure-webserver, type: multiselect, val: apache2}
      become: yes

    - name: first round of HSS apt install
      apt:
        name: "{{ item }}"
      with_items:
      - autoconf
      - automake
      - bison
      - build-essential
      - cmake
      - cmake-curses-gui
      - doxygen
      - doxygen-gui
      - flex
      - gdb
      - pkg-config
      - git
      - subversion
      - libconfig8-dev
      - libgcrypt11-dev
      - libidn2-0-dev
      - libidn11-dev
      - libmysqlclient-dev
      - libpthread-stubs0-dev
      - libsctp1
      - libsctp-dev
      - libssl-dev
      - libtool
      - mysql-client
      - mysql-server
      - openssl
      - nettle-dev
      - nettle-bin
      - python-mysqldb
      become: yes

    - name: MySQL Configs
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        host: localhost
        priv: '*.*:ALL'
      become: yes

# INSTALL FD
    - import_tasks: freediameter.yml

# INSTALL DATABASE AND PHPMYADMIN
    - name: second round of HSS apt install
      apt:
        name: "{{ item }}"
      with_items:
      - php
      - phpmyadmin
      - python-pexpect
      - libapache2-mod-php*
      become: yes

############################################################################
################################## MME #####################################
############################################################################

    - name: first round of MME apt install
      apt:
        name: "{{ item }}"
      with_items:
      - castxml
      - guile-2.0-dev
      - libgmp-dev
      - libhogweed?
      - libgtk-3-dev
      - libxml2
      - libxml2-dev
      - mscgen
      - check
      - python
      - libgnutls28-dev
      become: yes

    - import_tasks: asn1c.yml

    - import_tasks: libgtpnl.yml

    - name: second round of MME apt install
      apt:
        name: "{{ item }}"
      with_items:
      - ethtool
      - iproute
      - vlan
      - tshark
      - python-dev
      - unzip
      - iperf
      become: yes

############################################################################
################################## SPGW ####################################
############################################################################

# (NOTHING left at this point! Just iperf!)

############################################################################
################################## EPC #####################################
############################################################################

    - name: fetch epc from github
      git:
        repo: https://github.com/spencersevilla/enbrains-epc.git
        dest: /home/"{{ username }}"/epc

    - name: build epc with enbrains
      shell: |
        source oaienv
        ./scripts/build_hss -e
        ./scripts/build_mme -e
        ./scripts/build_spgw -e
      args:
        chdir: /home/"{{ username }}"/epc        

    - name: post-install config
      shell: |
        source /home/"{{ username }}"/epc/oaienv
        mkdir -p /usr/local/etc/oai
        cp -rp /home/"{{ username }}"/epc/spencer_configs/*.conf /usr/local/etc/oai/
        cp -rp /home/"{{ username }}"/epc/spencer_configs/freeDiameter /usr/local/etc/oai/
        /home/"{{ username }}"/epc/scripts/check_hss_s6a_certificate /usr/local/etc/oai/freeDiameter hss.OpenAir5G.Alliance
        /home/"{{ username }}"/epc/scripts/check_mme_s6a_certificate /usr/local/etc/oai/freeDiameter mme.OpenAir5G.Alliance
        /home/"{{ username }}"/epc/scripts/hss_db_import 127.0.0.1 "{{ mysql_user }}" "{{ mysql_password }}" oai_db /home/"{{ username }}"/epc/spencer_configs/sample_db.sql
      become: yes

############################################################################
############################# ENBRAINS #####################################
############################################################################

    - name: enbrains - apt-get dependencies
      apt:
        name: "libevent-dev"
      become: yes

    - name: enbrains - fetch from github
      git:
        repo: https://github.com/spencersevilla/enbrains.git
        dest: /home/"{{ username }}"/enbrains

    - name: enbrains - build
      make:
      chdir: /home/"{{ username }}"/enbrains


